[package]
name = "hello"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies]

[dependencies.bevy]
version = "0.6"
features = [
    "dynamic",
    "wayland",
]

[dependencies.bevy_rapier3d]
version = "0.12"
features = [
    "parallel",
    "simd-nightly",
]
