[package]
name = "eia3de_client"
version = "0.1.0"
authors = ["ldesgoui <ldesgoui@gmail.com>"]
edition = "2018"

[dependencies]
amethyst = "0.12"
log = "0.4"
simple_logger = "1.0"

[features]
default = ["amethyst/vulkan"]
